name: Build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  container:
    name: Container
    runs-on: forgejo-build
    steps:
      - name: Check out repository
        uses: https://data.forgejo.org/actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
        with:
          persist-credentials: false

      - name: Set up Buildx
        uses: https://data.forgejo.org/docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c

      - name: Build container
        uses: https://data.forgejo.org/docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: .
          push: false
          tags: activity-relay-directory:validation
          build-args: |
            VERSION=validation
