name: Build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  container:
    name: Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - name: Build container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: activity-relay-directory:validation
          build-args: |
            VERSION=validation
